CREATE TABLE [dbo].[Formula](
	[FormulaId] [uniqueidentifier] NOT NULL,
	[Name] [varchar](300) NOT NULL,
 CONSTRAINT [PK_Formula] PRIMARY KEY NONCLUSTERED 
(
	[FormulaId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]