CREATE TABLE [dbo].[SystemUser](
	[SystemUserId] [uniqueidentifier] NOT NULL,
	[LoginName] [varchar](100) NOT NULL,
 CONSTRAINT [PK_SystemUser] PRIMARY KEY NONCLUSTERED 
(
	[SystemUserId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]