//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Abacus.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Abacus.Localisation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation &apos;{0}&apos; depends on calculation &apos;{1}&apos; but this will cause a circular dependency.  Current dependency chain is: &apos;{2}&apos;..
        /// </summary>
        public static string CalculationCircularDependencyException {
            get {
                return ResourceManager.GetString("CalculationCircularDependencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations cannot depend on themselves.  Applies to calculation with name &apos;{0}&apos;..
        /// </summary>
        public static string CalculationDependencyOnSelfException {
            get {
                return ResourceManager.GetString("CalculationDependencyOnSelfException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to build a query has been made but the query contains no columns..
        /// </summary>
        public static string CannotBuildQueryWithNoColumns {
            get {
                return ResourceManager.GetString("CannotBuildQueryWithNoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Name.
        /// </summary>
        public static string ColumnText_AnswerName {
            get {
                return ResourceManager.GetString("ColumnText_AnswerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Type.
        /// </summary>
        public static string ColumnText_AnswerType {
            get {
                return ResourceManager.GetString("ColumnText_AnswerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ColumnText_Code {
            get {
                return ResourceManager.GetString("ColumnText_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ColumnText_Description {
            get {
                return ResourceManager.GetString("ColumnText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Result.
        /// </summary>
        public static string ColumnText_ExpectedResult {
            get {
                return ResourceManager.GetString("ColumnText_ExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Data?.
        /// </summary>
        public static string ColumnText_IsSystemData {
            get {
                return ResourceManager.GetString("ColumnText_IsSystemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name.
        /// </summary>
        public static string ColumnText_LoginName {
            get {
                return ResourceManager.GetString("ColumnText_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Name.
        /// </summary>
        public static string ColumnText_MethodName {
            get {
                return ResourceManager.GetString("ColumnText_MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnText_Name {
            get {
                return ResourceManager.GetString("ColumnText_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string ColumnText_Operation {
            get {
                return ResourceManager.GetString("ColumnText_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColumnText_Status {
            get {
                return ResourceManager.GetString("ColumnText_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ColumnText_Text {
            get {
                return ResourceManager.GetString("ColumnText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Source.
        /// </summary>
        public static string ColumnText_ValueSource {
            get {
                return ResourceManager.GetString("ColumnText_ValueSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Number.
        /// </summary>
        public static string ColumnText_VersionNumber {
            get {
                return ResourceManager.GetString("ColumnText_VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required connection string with name &apos;Abacus&apos; is not specified in the application configuration file..
        /// </summary>
        public static string ConnectionStringMissing {
            get {
                return ResourceManager.GetString("ConnectionStringMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method with action name &apos;{0}&apos; could be found on {1}Controller..
        /// </summary>
        public static string ControllerActionNotFound {
            get {
                return ResourceManager.GetString("ControllerActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not end with the word &apos;Controller&apos; but is implements the IController interface..
        /// </summary>
        public static string ControllerNameConventionException {
            get {
                return ResourceManager.GetString("ControllerNameConventionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0}Controller could not be located and has therefore not been loaded..
        /// </summary>
        public static string ControllerNotLoadedException {
            get {
                return ResourceManager.GetString("ControllerNotLoadedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No control validator could be found that handles control type &apos;{0}&apos;..
        /// </summary>
        public static string ControlValidatorNotFound {
            get {
                return ResourceManager.GetString("ControlValidatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new &apos;{0}&apos; QueryBuilder implementation could not be returned from the factory..
        /// </summary>
        public static string CouldNotCreateQueryBuilder {
            get {
                return ResourceManager.GetString("CouldNotCreateQueryBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a date/time value..
        /// </summary>
        public static string DateTimeRule {
            get {
                return ResourceManager.GetString("DateTimeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert DbType {0} to an equivalent {1}..
        /// </summary>
        public static string DbTypeConversionError {
            get {
                return ResourceManager.GetString("DbTypeConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a decimal value..
        /// </summary>
        public static string DecimalRule {
            get {
                return ResourceManager.GetString("DecimalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required &apos;DependencyResolverType&apos; setting in the application configuration file is either missing, invalid, or indicates a type that does not implement ICommand..
        /// </summary>
        public static string DependencyResolverTypeProblem {
            get {
                return ResourceManager.GetString("DependencyResolverTypeProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation since it will result in a duplicate &apos;{0}&apos; since there is already an entity attribute &apos;{1}&apos; with value &apos;{2}&apos;..
        /// </summary>
        public static string DuplicateEntityException {
            get {
                return ResourceManager.GetString("DuplicateEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; already exists in collection &apos;{1}&apos;..
        /// </summary>
        public static string DuplicateEntryException {
            get {
                return ResourceManager.GetString("DuplicateEntryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #,##0.00.
        /// </summary>
        public static string FormatDecimal {
            get {
                return ResourceManager.GetString("FormatDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a formula to execute for calculation &apos;{0}&apos;..
        /// </summary>
        public static string FormulaResolutionException {
            get {
                return ResourceManager.GetString("FormulaResolutionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Argument {
            get {
                object obj = ResourceManager.GetObject("Image_Argument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_ArgumentDelete {
            get {
                object obj = ResourceManager.GetObject("Image_ArgumentDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_ArgumentEdit {
            get {
                object obj = ResourceManager.GetObject("Image_ArgumentEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_ArgumentNew {
            get {
                object obj = ResourceManager.GetObject("Image_ArgumentNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_ArgumentRestrictedAnswer {
            get {
                object obj = ResourceManager.GetObject("Image_ArgumentRestrictedAnswer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Calculation {
            get {
                object obj = ResourceManager.GetObject("Image_Calculation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_CalculationDelete {
            get {
                object obj = ResourceManager.GetObject("Image_CalculationDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_CalculationEdit {
            get {
                object obj = ResourceManager.GetObject("Image_CalculationEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_CalculationNew {
            get {
                object obj = ResourceManager.GetObject("Image_CalculationNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_ChangeOrder {
            get {
                object obj = ResourceManager.GetObject("Image_ChangeOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Constraint {
            get {
                object obj = ResourceManager.GetObject("Image_Constraint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_ConstraintDelete {
            get {
                object obj = ResourceManager.GetObject("Image_ConstraintDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_ConstraintEdit {
            get {
                object obj = ResourceManager.GetObject("Image_ConstraintEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_ConstraintNew {
            get {
                object obj = ResourceManager.GetObject("Image_ConstraintNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Copy {
            get {
                object obj = ResourceManager.GetObject("Image_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_DecimalTable {
            get {
                object obj = ResourceManager.GetObject("Image_DecimalTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_DecimalTableDelete {
            get {
                object obj = ResourceManager.GetObject("Image_DecimalTableDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_DecimalTableEdit {
            get {
                object obj = ResourceManager.GetObject("Image_DecimalTableEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_DecimalTableNew {
            get {
                object obj = ResourceManager.GetObject("Image_DecimalTableNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_DownArrow {
            get {
                object obj = ResourceManager.GetObject("Image_DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Error {
            get {
                object obj = ResourceManager.GetObject("Image_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Errorx {
            get {
                object obj = ResourceManager.GetObject("Image_Errorx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Exit {
            get {
                object obj = ResourceManager.GetObject("Image_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Flush {
            get {
                object obj = ResourceManager.GetObject("Image_Flush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Formula {
            get {
                object obj = ResourceManager.GetObject("Image_Formula", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_FormulaDelete {
            get {
                object obj = ResourceManager.GetObject("Image_FormulaDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_FormulaEdit {
            get {
                object obj = ResourceManager.GetObject("Image_FormulaEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_FormulaNew {
            get {
                object obj = ResourceManager.GetObject("Image_FormulaNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Grab {
            get {
                object obj = ResourceManager.GetObject("Image_Grab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Hourglass {
            get {
                object obj = ResourceManager.GetObject("Image_Hourglass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Limit {
            get {
                object obj = ResourceManager.GetObject("Image_Limit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_LimitDelete {
            get {
                object obj = ResourceManager.GetObject("Image_LimitDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_LimitEdit {
            get {
                object obj = ResourceManager.GetObject("Image_LimitEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_LimitNew {
            get {
                object obj = ResourceManager.GetObject("Image_LimitNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Mark {
            get {
                object obj = ResourceManager.GetObject("Image_Mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Method {
            get {
                object obj = ResourceManager.GetObject("Image_Method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_MethodDelete {
            get {
                object obj = ResourceManager.GetObject("Image_MethodDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_MethodEdit {
            get {
                object obj = ResourceManager.GetObject("Image_MethodEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_MethodNew {
            get {
                object obj = ResourceManager.GetObject("Image_MethodNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_MethodTest {
            get {
                object obj = ResourceManager.GetObject("Image_MethodTest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_MethodTestDelete {
            get {
                object obj = ResourceManager.GetObject("Image_MethodTestDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_MethodTestEdit {
            get {
                object obj = ResourceManager.GetObject("Image_MethodTestEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_MethodTestError {
            get {
                object obj = ResourceManager.GetObject("Image_MethodTestError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_MethodTestNew {
            get {
                object obj = ResourceManager.GetObject("Image_MethodTestNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_MethodTestRun {
            get {
                object obj = ResourceManager.GetObject("Image_MethodTestRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Permissions {
            get {
                object obj = ResourceManager.GetObject("Image_Permissions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_PermissionsEdit {
            get {
                object obj = ResourceManager.GetObject("Image_PermissionsEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Presenter {
            get {
                object obj = ResourceManager.GetObject("Image_Presenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_RefreshSmall {
            get {
                object obj = ResourceManager.GetObject("Image_RefreshSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Report {
            get {
                object obj = ResourceManager.GetObject("Image_Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Show {
            get {
                object obj = ResourceManager.GetObject("Image_Show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Submit {
            get {
                object obj = ResourceManager.GetObject("Image_Submit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_SystemUser {
            get {
                object obj = ResourceManager.GetObject("Image_SystemUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_SystemUserDelete {
            get {
                object obj = ResourceManager.GetObject("Image_SystemUserDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_SystemUserEdit {
            get {
                object obj = ResourceManager.GetObject("Image_SystemUserEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_SystemUserNew {
            get {
                object obj = ResourceManager.GetObject("Image_SystemUserNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_UpArrow {
            get {
                object obj = ResourceManager.GetObject("Image_UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation input type &apos;{0}&apos; cannot be compared to type &apos;{1}&apos;..
        /// </summary>
        public static string IncompatibleCalculationValues {
            get {
                return ResourceManager.GetString("IncompatibleCalculationValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer value..
        /// </summary>
        public static string IntegerRule {
            get {
                return ResourceManager.GetString("IntegerRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve an implementation of an {0}..
        /// </summary>
        public static string InterfaceResolutionException {
            get {
                return ResourceManager.GetString("InterfaceResolutionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IView type &apos;{0}&apos; is not a control..
        /// </summary>
        public static string IViewNotAControl {
            get {
                return ResourceManager.GetString("IViewNotAControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; could not be found in collection &apos;{1}&apos;..
        /// </summary>
        public static string KeyNotFoundException {
            get {
                return ResourceManager.GetString("KeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May not be longer than {0} characters..
        /// </summary>
        public static string MaximumLengthRule {
            get {
                return ResourceManager.GetString("MaximumLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least {0} characters long..
        /// </summary>
        public static string MinimumLengthRule {
            get {
                return ResourceManager.GetString("MinimumLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &apos;{0}&apos; with id &apos;{1}&apos; could not be located..
        /// </summary>
        public static string MissingEntityException {
            get {
                return ResourceManager.GetString("MissingEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; not found in collection &apos;{1}&apos;..
        /// </summary>
        public static string MissingEntryException {
            get {
                return ResourceManager.GetString("MissingEntryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a money value..
        /// </summary>
        public static string MoneyRule {
            get {
                return ResourceManager.GetString("MoneyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No navigation item has been registered that corresponds to message type &apos;{0}&apos;..
        /// </summary>
        public static string NavigationItemNotFoundForMessage {
            get {
                return ResourceManager.GetString("NavigationItemNotFoundForMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; does not follow the NavigationItemProvider naming convention..
        /// </summary>
        public static string NavigationItemProviderNameConventionBroken {
            get {
                return ResourceManager.GetString("NavigationItemProviderNameConventionBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current unit of work in your context.  Please contact development support..
        /// </summary>
        public static string NoUnitOfWork {
            get {
                return ResourceManager.GetString("NoUnitOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No view has been attached to presenter type &apos;{0}&apos; but the view has been requested..
        /// </summary>
        public static string NoViewAttachedToPresenter {
            get {
                return ResourceManager.GetString("NoViewAttachedToPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency &apos;{0}&apos; has been accessed but it has not been set..
        /// </summary>
        public static string NullDependencyException {
            get {
                return ResourceManager.GetString("NullDependencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required value is null: {0}.
        /// </summary>
        public static string NullReferenceException {
            get {
                return ResourceManager.GetString("NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe casting from &apos;{0}&apos; to &apos;{1}&apos; resulted in a null..
        /// </summary>
        public static string NullSafeCasting {
            get {
                return ResourceManager.GetString("NullSafeCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to assign a value to &apos;{0}&apos; but it has already been assigned a value..
        /// </summary>
        public static string ReassignmentException {
            get {
                return ResourceManager.GetString("ReassignmentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository for entity &apos;{0}&apos; could not be located in the dependency injection container..
        /// </summary>
        public static string RepositoryNotFound {
            get {
                return ResourceManager.GetString("RepositoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required..
        /// </summary>
        public static string RequiredRule {
            get {
                return ResourceManager.GetString("RequiredRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not determine ResourceItem for Message name &apos;{0}&apos;..
        /// </summary>
        public static string ResourceItemForMessageError {
            get {
                return ResourceManager.GetString("ResourceItemForMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string argument {0} must not be empty..
        /// </summary>
        public static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Administration.
        /// </summary>
        public static string Text_Administration {
            get {
                return ResourceManager.GetString("Text_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change &amp;Order.
        /// </summary>
        public static string Text_ChangeOrder {
            get {
                return ResourceManager.GetString("Text_ChangeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string Text_Copy {
            get {
                return ResourceManager.GetString("Text_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        public static string Text_Delete {
            get {
                return ResourceManager.GetString("Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Login Name.
        /// </summary>
        public static string Text_EditLoginName {
            get {
                return ResourceManager.GetString("Text_EditLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Permissions.
        /// </summary>
        public static string Text_EditPermissions {
            get {
                return ResourceManager.GetString("Text_EditPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Text_Exit {
            get {
                return ResourceManager.GetString("Text_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string Text_File {
            get {
                return ResourceManager.GetString("Text_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Grab Other Calculations.
        /// </summary>
        public static string Text_GrabCalculations {
            get {
                return ResourceManager.GetString("Text_GrabCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string Text_Help {
            get {
                return ResourceManager.GetString("Text_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Marks.
        /// </summary>
        public static string Text_InvertMarks {
            get {
                return ResourceManager.GetString("Text_InvertMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;List.
        /// </summary>
        public static string Text_List {
            get {
                return ResourceManager.GetString("Text_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manage.
        /// </summary>
        public static string Text_Manage {
            get {
                return ResourceManager.GetString("Text_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manual.
        /// </summary>
        public static string Text_Manual {
            get {
                return ResourceManager.GetString("Text_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All.
        /// </summary>
        public static string Text_MarkAll {
            get {
                return ResourceManager.GetString("Text_MarkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;Down.
        /// </summary>
        public static string Text_MoveDown {
            get {
                return ResourceManager.GetString("Text_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move &amp;Up.
        /// </summary>
        public static string Text_MoveUp {
            get {
                return ResourceManager.GetString("Text_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string Text_New {
            get {
                return ResourceManager.GetString("Text_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New From Selected.
        /// </summary>
        public static string Text_NewFromSelected {
            get {
                return ResourceManager.GetString("Text_NewFromSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New From This (Copy).
        /// </summary>
        public static string Text_NewFromThis {
            get {
                return ResourceManager.GetString("Text_NewFromThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        public static string Text_Print {
            get {
                return ResourceManager.GetString("Text_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Text_Process {
            get {
                return ResourceManager.GetString("Text_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        public static string Text_Remove {
            get {
                return ResourceManager.GetString("Text_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Report.
        /// </summary>
        public static string Text_Report {
            get {
                return ResourceManager.GetString("Text_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Table Report.
        /// </summary>
        public static string Text_ReportDecimalTable {
            get {
                return ResourceManager.GetString("Text_ReportDecimalTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Text_Run {
            get {
                return ResourceManager.GetString("Text_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show Summary View.
        /// </summary>
        public static string Text_ShowSummaryView {
            get {
                return ResourceManager.GetString("Text_ShowSummaryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        public static string Text_Start {
            get {
                return ResourceManager.GetString("Text_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Submit.
        /// </summary>
        public static string Text_Submit {
            get {
                return ResourceManager.GetString("Text_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;System.
        /// </summary>
        public static string Text_System {
            get {
                return ResourceManager.GetString("Text_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Users.
        /// </summary>
        public static string Text_Users {
            get {
                return ResourceManager.GetString("Text_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        public static string Text_View {
            get {
                return ResourceManager.GetString("Text_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a required value in &apos;{1}&apos;..
        /// </summary>
        public static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a workspace of type &apos;{0}&apos;..
        /// </summary>
        public static string WorkspaceNotFound {
            get {
                return ResourceManager.GetString("WorkspaceNotFound", resourceCulture);
            }
        }
    }
}
