delete from ArgumentValue
delete from Argument
delete from AnswerType
delete from ConstraintType
delete from OperationType
delete from ValueSourceType
delete from Matrix
delete from MatrixElement
delete from FormulaOperation
delete from GraphNodeArgument
delete from FormulaConstraint
--delete from SystemUser
--delete from SystemUserPermission
delete from TestArgumentValue
delete from ProjectionPosition
delete from Formula
delete from Test