// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shuttle.Abacus.SqlServer;

#nullable disable

namespace Shuttle.Abacus.SqlServer.Migrations
{
    [DbContext(typeof(AbacusDbContext))]
    [Migration("20260913070356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.Algorithm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaximumAlgorithmName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MinimumAlgorithmName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UX_Algorithm_Name")
                        .IsUnique();

                    b.ToTable("Algorithm", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.AlgorithmConstraint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlgorithmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArgumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comparison")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmId");

                    b.ToTable("AlgorithmConstraint", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.AlgorithmOperation", b =>
                {
                    b.Property<Guid>("AlgorithmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InputParameter")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ValueProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlgorithmId", "SequenceNumber");

                    b.HasIndex(new[] { "Id" }, "UX_AlgorithmOperation_Id")
                        .IsUnique();

                    b.ToTable("AlgorithmOperation", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.Argument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UX_Argument_Name")
                        .IsUnique();

                    b.ToTable("Argument", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.ArgumentValue", b =>
                {
                    b.Property<Guid>("ArgumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ArgumentId", "Value");

                    b.ToTable("ArgumentValue", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.Matrix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ColumnArgumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("RowArgumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UX_Matrix_Name")
                        .IsUnique();

                    b.ToTable("Matrix", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.MatrixConstraint", b =>
                {
                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Axis")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Comparison")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MatrixId", "Axis", "Index");

                    b.HasIndex(new[] { "Id" }, "UX_MatrixConstraint_Id")
                        .IsUnique();

                    b.ToTable("MatrixConstraint", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.MatrixElement", b =>
                {
                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MatrixId", "Row", "Column");

                    b.HasIndex(new[] { "Id" }, "UX_MatrixElement_Id")
                        .IsUnique();

                    b.ToTable("MatrixElement", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlgorithmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comparison")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExpectedResultDataTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UX_Test_Name")
                        .IsUnique();

                    b.ToTable("Test", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.TestArgument", b =>
                {
                    b.Property<Guid>("TestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArgumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TestId", "ArgumentId");

                    b.ToTable("TestArgument", "abacus");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.AlgorithmConstraint", b =>
                {
                    b.HasOne("Shuttle.Abacus.SqlServer.Models.Algorithm", "Algorithm")
                        .WithMany("Constraints")
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Algorithm");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.AlgorithmOperation", b =>
                {
                    b.HasOne("Shuttle.Abacus.SqlServer.Models.Algorithm", "Algorithm")
                        .WithMany("Operations")
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Algorithm");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.ArgumentValue", b =>
                {
                    b.HasOne("Shuttle.Abacus.SqlServer.Models.Argument", "Argument")
                        .WithMany("Values")
                        .HasForeignKey("ArgumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Argument");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.MatrixConstraint", b =>
                {
                    b.HasOne("Shuttle.Abacus.SqlServer.Models.Matrix", "Matrix")
                        .WithMany("Constraints")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.MatrixElement", b =>
                {
                    b.HasOne("Shuttle.Abacus.SqlServer.Models.Matrix", "Matrix")
                        .WithMany("Elements")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.TestArgument", b =>
                {
                    b.HasOne("Shuttle.Abacus.SqlServer.Models.Test", "Test")
                        .WithMany("Arguments")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.Algorithm", b =>
                {
                    b.Navigation("Constraints");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.Argument", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.Matrix", b =>
                {
                    b.Navigation("Constraints");

                    b.Navigation("Elements");
                });

            modelBuilder.Entity("Shuttle.Abacus.SqlServer.Models.Test", b =>
                {
                    b.Navigation("Arguments");
                });
#pragma warning restore 612, 618
        }
    }
}
